<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Nwp.InvoiceAutomation.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Update="data\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.Identity.Web" Version="2.20.0" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="2.20.0" />
  </ItemGroup>
</Project>
